name: Create a release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:release-3_34
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Fix Python command
        run: apt-get install python-is-python3

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install plugin dependencies
        run: poetry install

      - name: Get experimental info
        id: get-experimental
        run: |
          is_experimental=$(poetry run python - <<'PY'
          import toml
          data = toml.load("pyproject.toml")
          print(data["tool"]["qgis-plugin"]["metadata"]["experimental"].lower())
          PY
          )
          echo "IS_EXPERIMENTAL=${is_experimental}" >> "$GITHUB_OUTPUT"

      - name: Generate zip
        run: poetry run python admin.py generate-zip

      - name: Create release from tag and upload zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.get-experimental.outputs.IS_EXPERIMENTAL == 'true' }}
          files: dist/*.zip

      - name: Generate plugin repo XML
        run: poetry run python admin.py --verbose generate-plugin-repo-xml

      - name: Update release repository
        run: poetry run mkdocs gh-deploy --force
